version: "3.9"
services:
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: oxid
      MYSQL_PASSWORD: oxid
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  oxid:
    image: endereco/oxid_ce:6.4.1
    environment:
      SHOP_URL: http://localhost
    volumes:
      - ./:/var/www/html/custom/eurotext/translationmanager6
      - ./:/var/www/html/source/modules/eurotext/translationmanager6
    ports:
      - 80:80
    depends_on:
      mysql:
        condition: service_healthy
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080