<?php

$sMetadataVersion = '2.0';
$aModule = array(
    'id'           => 'translationmanager6',
    'title'        => 'Eurotext Translationmanager',
    'description'  => array(
        'de' => 'Modul für die Übersetzung von Shoptexten.',
        'en' => 'Module for the text translation.',
    ),
    'thumbnail'    => 'logo.jpg',
    'version'      => '2.3.0',
    'author'       => 'mobilemojo – Apps & eCommerce UG (haftungsbeschränkt) & Co. KG',
    'url'          => 'https://www.mobilemojo.de',
    'email'        => 'info@mobilemojo.de',
    'controllers' => array(
        'translationmanager_export' => \Eurotext\Translationmanager\Controller\Admin\Export::class,
        'translationmanager_export_detail' => \Eurotext\Translationmanager\Controller\Admin\ExportDetail::class,
        'translationmanager_export_list' => \Eurotext\Translationmanager\Controller\Admin\ExportList::class,
        'translationmanager_import' => \Eurotext\Translationmanager\Controller\Admin\Import::class,
        'translationmanager_import_detail' => \Eurotext\Translationmanager\Controller\Admin\ImportDetail::class,
        'translationmanager_import_list' => \Eurotext\Translationmanager\Controller\Admin\ImportList::class,
        'translationmanager_settings' => \Eurotext\Translationmanager\Controller\Admin\Settings::class,
        'translationmanager_registration' => \Eurotext\Translationmanager\Controller\Admin\Registration::class,
        'translationmanager_help' => \Eurotext\Translationmanager\Controller\Admin\Help::class,
        'translationmanager_cms_selection' => \Eurotext\Translationmanager\Controller\Admin\Popup\CmsSelectionMain::class,
        'translationmanager_cms_selection_ajax' => \Eurotext\Translationmanager\Controller\Admin\Popup\CmsSelectionAjax::class,
        'translationmanager_articles_selection' => \Eurotext\Translationmanager\Controller\Admin\Popup\ArticlesSelectionMain::class,
        'translationmanager_articles_selection_ajax' => \Eurotext\Translationmanager\Controller\Admin\Popup\ArticlesSelectionAjax::class,
        'translationmanager_attributes_selection' => \Eurotext\Translationmanager\Controller\Admin\Popup\AttributesSelectionMain::class,
        'translationmanager_attributes_selection_ajax' => \Eurotext\Translationmanager\Controller\Admin\Popup\AttributesSelectionAjax::class,
        'translationmanager_categories_selection' => \Eurotext\Translationmanager\Controller\Admin\Popup\CategoriesSelectionMain::class,
        'translationmanager_categories_selection_ajax' => \Eurotext\Translationmanager\Controller\Admin\Popup\CategoriesSelectionAjax::class,
    ),
    'templates' => array(
        'translationmanager6_settings.tpl' => 'eurotext/translationmanager6/application/views/admin/tpl/translationmanager_settings.tpl',
        'translationmanager6_registration.tpl' => 'eurotext/translationmanager6/application/views/admin/tpl/translationmanager_registration.tpl',
        'translationmanager6_help.tpl' => 'eurotext/translationmanager6/application/views/admin/tpl/translationmanager_help.tpl',
        'translationmanager6_export.tpl' => 'eurotext/translationmanager6/application/views/admin/tpl/translationmanager_export.tpl',
        'translationmanager6_export_list.tpl' => 'eurotext/translationmanager6/application/views/admin/tpl/translationmanager_export_list.tpl',
        'translationmanager6_export_detail.tpl' => 'eurotext/translationmanager6/application/views/admin/tpl/translationmanager_export_detail.tpl',
        'translationmanager6_import.tpl' => 'eurotext/translationmanager6/application/views/admin/tpl/translationmanager_import.tpl',
        'translationmanager6_import_list.tpl' => 'eurotext/translationmanager6/application/views/admin/tpl/translationmanager_import_list.tpl',
        'translationmanager6_import_detail.tpl' => 'eurotext/translationmanager6/application/views/admin/tpl/translationmanager_import_detail.tpl',
        'translationmanager6_cms_selection_detail.tpl' => 'eurotext/translationmanager6/application/views/admin/tpl/popup/translationmanager_cms_selection_detail.tpl',
        'translationmanager6_articles_selection_detail.tpl' => 'eurotext/translationmanager6/application/views/admin/tpl/popup/translationmanager_articles_selection_detail.tpl',
        'translationmanager6_attributes_selection_detail.tpl' => 'eurotext/translationmanager6/application/views/admin/tpl/popup/translationmanager_attributes_selection_detail.tpl',
        'translationmanager6_categories_selection_detail.tpl' => 'eurotext/translationmanager6/application/views/admin/tpl/popup/translationmanager_categories_selection_detail.tpl',
    ),
    'events' => array(
        'onActivate' => '\Eurotext\Translationmanager\Core\Installer::onActivate',
        'onDeactivate' => '\Eurotext\Translationmanager\Core\Installer::onDeactivate',
    ),
    'blocks' => array(
        array(
            'template' => 'bottomnaviitem.tpl',
            'block'    => 'admin_bottomnavicustom',
            'file'     => '/application/views/blocks/bottomnavi.tpl'
        )
    ),
    'settings' => array(
        array('group' => 'main', 'name' => 'sCONNSTATUS', 'type' => 'str', 'value' => '0'),
        array('group' => 'main', 'name' => 'sAPIKEY', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sSERVICEURL', 'type' => 'str', 'value' => 'https://sandbox.api.eurotext.de'),

        array('group' => 'main', 'name' => 'cmsfields', 'type' => 'arr', 'value' => array('OXTITLE', 'OXCONTENT')),
        array('group' => 'main', 'name' => 'categoryfields', 'type' => 'arr', 'value' => array('OXTITLE', 'OXDESC', 'OXLONGDESC')),
        array('group' => 'main', 'name' => 'attributesfields', 'type' => 'arr', 'value' => array('OXTITLE')),
        array('group' => 'main', 'name' => 'o2attributesfields', 'type' => 'arr', 'value' => array('OXVALUE')),
        array('group' => 'main', 'name' => 'articlesfields', 'type' => 'arr', 'value' => array('OXTITLE', 'OXSHORTDESC', 'OXVARNAME', 'OXVARSELECT')),
        array('group' => 'main', 'name' => 'artextendsfields', 'type' => 'arr', 'value' => array('OXLONGDESC')),
        array('group' => 'main', 'name' => 'cmsseofields', 'type' => 'arr', 'value' => array()),
        array('group' => 'main', 'name' => 'categoryseofields', 'type' => 'arr', 'value' => array()),
        array('group' => 'main', 'name' => 'articleseofields', 'type' => 'arr', 'value' => array()),

        array('group' => 'main', 'name' => 'sEttmLang_de', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_en', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_fr', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_ab', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_aa', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_af', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_ak', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_sq', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_am', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_ar', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_an', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_hy', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_as', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_av', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_ae', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_ay', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_az', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_bm', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_ba', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_eu', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_be', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_bn', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_bh', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_bi', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_bs', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_br', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_bg', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_my', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_ca', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_ch', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_ce', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_ny', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_zh', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_cv', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_kw', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_co', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_cr', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_hr', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_cs', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_da', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_dv', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_nl', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_dz', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_eo', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_et', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_ee', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_fo', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_fj', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_fi', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_ff', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_gl', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_ka', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_el', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_gn', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_gu', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_ht', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_ha', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_he', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_hz', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_hi', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_ho', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_hu', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_ia', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_id', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_ie', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_ga', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_ig', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_ik', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_io', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_is', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_it', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_iu', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_ja', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_jv', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_kl', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_kn', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_kr', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_ks', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_kk', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_km', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_ki', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_rw', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_ky', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_kv', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_kg', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_ko', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_ku', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_kj', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_la', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_lb', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_lg', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_li', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_ln', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_lo', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_lt', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_lu', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_lv', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_gv', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_mk', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_mg', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_ms', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_ml', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_mt', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_mi', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_mr', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_mh', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_mn', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_na', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_nv', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_nd', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_ne', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_ng', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_nb', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_nn', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_no', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_ii', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_nr', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_oc', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_oj', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_cu', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_om', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_or', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_os', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_pa', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_pi', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_fa', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_pl', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_ps', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_pt', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_qu', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_rm', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_rn', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_ro', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_ru', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_sa', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_sc', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_sd', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_se', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_sh', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_sm', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_sg', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_sr', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_gd', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_sn', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_si', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_sk', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_sl', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_so', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_st', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_es', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_su', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_sw', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_ss', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_sv', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_ta', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_te', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_tg', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_th', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_ti', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_bo', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_tk', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_tl', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_tn', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_to', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_tr', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_ts', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_tt', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_tw', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_ty', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_ug', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_uk', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_ur', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_uz', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_ve', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_vi', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_vo', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_wa', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_cy', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_wo', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_fy', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_xh', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_yi', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_yo', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_za', 'type' => 'str', 'value' => ''),
        array('group' => 'main', 'name' => 'sEttmLang_zu', 'type' => 'str', 'value' => ''),

        array('group' => 'main', 'name' => 'sEXPORTJOBIPJ', 'type' => 'str', 'value' => '20'),
        array('group' => 'main', 'name' => 'sIMPORTJOBIPJ', 'type' => 'str', 'value' => '20'),
        array('group' => 'main', 'name' => 'sTRANSLATIONJOBIPJ', 'type' => 'str', 'value' => '20'),
    )
);
